package com.gallery.prdct;

import com.gallery.brand.BrandVo;
import com.gallery.shop.ShopVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PrdctMapper {
    void delinvn();
    void addPrdct(PrdctVo value);
    void delPrdctInvnHist(PrdctVo value);
    void comAllow(PrdctVo value);
    void modifyDate(PrdctVo value);
    void addPrdctColor(PrdctVo value);
    void modifyPrdct(PrdctVo value);
    Integer modifyPrdctAcpt(PrdctVo value);
    Integer modifyPrdctInvn(PrdctVo value);
    void addPrdctInvn(PrdctVo value);
    void addPrdctInvnHist(PrdctVo value);
    void removePrdct(PrdctVo value);
    void modifyPrdctPrc(PrdctVo value);
    void delData(PrdctVo value);
    void addInvn(PrdctVo value);
    void updateInvn(PrdctVo value);
    void InvnUpdate(PrdctVo value);
    void modifyInvnPrdct(PrdctVo value);
    void addNewClensAcc(PrdctVo value);
    void delCntInvn(PrdctVo value);
    void updateVideoCd(PrdctVo value);
    void updatePrdctImg(PrdctVo value);
    void addVideoCd(PrdctVo value);
    void addNewClens(PrdctVo value);
    void addNewLensData(PrdctVo value);
    void addNewLens(PrdctVo value);
    void addNewEtc(PrdctVo value);
    void addOrderList(PrdctVo value);
    void addShopInvnHist(PrdctVo value);
    void receivePrdct(PrdctVo value);
    void updateShopInvn(PrdctVo value);
    void newOrder(PrdctVo value);
    void candelOrder(PrdctVo value);
    List<PrdctVo> getRtnReasonList();
    void addNewLensTyId(PrdctVo value);
    void newRequestLens(PrdctVo value);
    void ReturnPrdct(PrdctVo value);
    void addShopInvn(PrdctVo value);
    void addNewRtnReason(PrdctVo value);
    void lensOrder(PrdctVo value);
    void lensComOrder(PrdctVo value);
    void modifySpareLensSpec(PrdctVo value);
    void addLensInbnHist(PrdctVo value);
    void modifyLensM(PrdctVo value);
    void addLensInvn(PrdctVo value);
    void updateLensInvn(PrdctVo value);
    void allowComOrder(PrdctVo value);
    void modDetail(PrdctVo value);
    void OrderRX(PrdctVo value);
    void modifyOption(PrdctVo value);
    PrdctVo getInvnEditForm(PrdctVo value);
    PrdctVo editLensRX(PrdctVo value);
    PrdctVo getOrderPrdctProp2(PrdctVo value);
    List<PrdctVo> getPrdctRanking(PrdctVo value);
    List<PrdctVo> getLensOrderList(PrdctVo value);
    PrdctVo getOrderPrdctProp(PrdctVo value);
    List<PrdctVo> getColorCom(PrdctVo value);
    List<PrdctVo> getLensColorList(PrdctVo value);
    List<PrdctVo> getRtnLens(PrdctVo value);
    List<PrdctVo> getNewLensOrderList(PrdctVo value);
    PrdctVo getLensBound(PrdctVo value);
    List<PrdctVo> getRtnLens2(PrdctVo value);
    List<PrdctVo> getRtnEtc(PrdctVo value);
    List<PrdctVo> getLensComList(PrdctVo value);
    List<PrdctVo> getRtnClens(PrdctVo value);
    List<PrdctVo> getLensListForOrder(PrdctVo value);
    List<PrdctVo> getRtnAcc(PrdctVo value);
    List<PrdctVo> getRtnFrame(PrdctVo value);
    List<PrdctVo> showAllLensType(PrdctVo value);
    List<PrdctVo> getLensListByType(PrdctVo value);
    List<PrdctVo> getRate(PrdctVo value);
    List<PrdctVo> getLensList(PrdctVo value);
    List<PrdctVo> getTradeData(PrdctVo value);
    List<PrdctVo> getReceiptLens2(PrdctVo value);
    List<PrdctVo> getReceiptAcc(PrdctVo value);
    List<PrdctVo> getReceiptHeader(PrdctVo value);
    List<PrdctVo> getReceipt(PrdctVo value);
    PrdctVo getPrdctType(PrdctVo value);
    List<PrdctVo> getReceiptLens(PrdctVo value);
    List<PrdctVo> getReceiptEtc(PrdctVo value);
    List<PrdctVo> getReceiptClens(PrdctVo value);
    List<PrdctVo> srchPrdct(PrdctVo value);
    List<PrdctVo> getOrderList(PrdctVo value);
    List<PrdctVo> getOrderNewLensList(PrdctVo value);
    PrdctVo getComPrdct(PrdctVo value);
    PrdctVo getMobilePrdctInfo(PrdctVo value);
    List<PrdctVo> getMobilePrdct(PrdctVo value);
    List<PrdctVo> getFunction(PrdctVo value);
    PrdctVo getPrdctPrc(PrdctVo value);
    List<PrdctVo> getTradeListForModify(PrdctVo value);
    List<PrdctVo> getMtrlListLens(PrdctVo value);
    PrdctVo getPrdctInvn(PrdctVo value);
    List<PrdctVo> pagedListPrdct(PrdctVo value);
    List<PrdctVo> listPrdctColor(PrdctVo value);
    List<PrdctVo> pagedListPrdctConfirm(PrdctVo value);
    List<PrdctVo> listPrdctForEvent(PrdctVo value);
    List<PrdctVo> pagedListPrdctRemain(PrdctVo value);
    List<PrdctVo> getComListByCntry(PrdctVo value);
    List<PrdctVo> pagedListPrdctInvnHist(PrdctVo value);
    List<PrdctVo> pagedListPrdctInvnHistOutPut(PrdctVo value);
    List<PrdctVo> mListFrame(PrdctVo value);
    List<PrdctVo> mListLens(PrdctVo value);
    List<PrdctVo> getComPrdctList(PrdctVo value);
    PrdctVo getPrdct(PrdctVo value);
    List<PrdctVo> getSelectLensDemo(PrdctVo value);
    PrdctVo getPrdctInvnHist(PrdctVo value);
    List<PrdctVo> mListPrdctTypeFrame(PrdctVo value);
    List<PrdctVo> mListDsplyLens(PrdctVo value);
    List<PrdctVo> getComListForOrd(PrdctVo value);
    PrdctVo getComPrdctEditForm(PrdctVo value);
    List<PrdctVo> getReqstPrdct(PrdctVo value);
    List<PrdctVo> getLensTyByCom(PrdctVo value);
    List<PrdctVo> invnHist(PrdctVo value);
    List<PrdctVo> getCntryList();
    List<PrdctVo> getColorList();
    List<PrdctVo> getMtrlList();
    List<PrdctVo> getPrdctOption(PrdctVo value);
    List<PrdctVo> getComOrderList(PrdctVo value);
    List<PrdctVo> showDetail(PrdctVo value);
    PrdctVo getShopName(PrdctVo value);
    List<PrdctVo> getLensSM(PrdctVo value);
    String shopInvn(PrdctVo value);
    String chkAdminAllow(PrdctVo value);
    String srchLensInvn(PrdctVo value);
    String getComOrderCnt(PrdctVo value);
    String srchPrdctTlb(PrdctVo value);
    String srchPrdctShopInvn(PrdctVo value);
    String srchPrdctInvn(PrdctVo value);
    String getDetail(PrdctVo value);
    String getVideoCd(Integer value);
    Integer countPrdct(PrdctVo value);
    Integer getPrdctPrice(PrdctVo value);
    Integer srchMatchClr(PrdctVo value);
    Integer getPrdctId(PrdctVo value);
    Integer pagedListPrdctInvnHistCount(PrdctVo value);
    Integer countPrdctColor(PrdctVo value);
    Integer pagedListPrdctConfirmCount(PrdctVo value);
    Integer pagedListPrdctCount(PrdctVo value);
    Integer countPrdctForBrand(BrandVo value);
    String getShopId(Integer value);
    List<PrdctVo> getPrdctListByBrand(BrandVo value);
    List<PrdctVo> getInvnList(ShopVo value);
    List<ShopVo> getTradeListByCom(ShopVo value);
}
