package com.gallery.web.prdct.service;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletResponse;

import com.gallery.web.brand.domain.BrandVo;
import com.gallery.web.company.domain.CompanyVo;
import com.gallery.web.prdct.domain.PrdctVo;
import com.gallery.web.shop.domain.ShopVo;

public interface PrdctService {
	public String addPrdct(PrdctVo prdctVo) throws Exception;
	public String addPrdctColor(PrdctVo prdctVo) throws Exception;
	public Integer countPrdctForBrand(BrandVo brandVo) throws Exception;
	public Integer countPrdctForCompany(CompanyVo companyVo) throws Exception;
	public void modifyPrdct(PrdctVo prdctVo) throws Exception;
	public String modifyPrdctAcpt(PrdctVo prdctVo) throws Exception;
	public String modifyPrdctInvn(PrdctVo prdctVo) throws Exception;
	public Map pagedListPrdctData(PrdctVo prdctVo) throws Exception;
	public Map listPrdctDataForEvent(PrdctVo prdctVo) throws Exception;
	public String listPrdctColor(PrdctVo prdctVo) throws Exception;
	public Map pagedListPrdctConfirmData(PrdctVo prdctVo) throws Exception;
	public Map pagedListPrdctRemainData(PrdctVo prdctVo) throws Exception;
	public Map pagedListPrdctInvnHistData(PrdctVo prdctVo) throws Exception;
	public PrdctVo selectPrdct(PrdctVo prdctVo) throws Exception;
	public PrdctVo selectPrdctInvnHist(PrdctVo prdctVo) throws Exception;
	public PrdctVo removePrdct(PrdctVo prdctVo) throws Exception;
	public void responseFrameData(PrdctVo prdctVo,HttpServletResponse response) throws Exception;
	public void responseLensData(PrdctVo prdctVo,HttpServletResponse response) throws Exception;
	public void responseDsplyLensData(PrdctVo prdctVo,HttpServletResponse response) throws Exception;
	public List <PrdctVo> selectLensPath(PrdctVo prdctVo) throws Exception;
	public void modifyPrdctPrc(PrdctVo prdctVo)throws Exception;
	public Map getPrdctListByBrand(BrandVo branVo)throws Exception;
	public Map getCntryList(PrdctVo prdctVo)throws Exception;
	public String addPrdctInvn(PrdctVo prdctVo)throws Exception; 
	public Map getInvnList(ShopVo shopVo)throws Exception;
	public Map getInvnHist(PrdctVo prdctVo)throws Exception;
	public Map getLensInvnHist(PrdctVo prdctVo)throws Exception;
	public Map getClensnvnHist(PrdctVo prdctVo)throws Exception;
	public Map getClensAccInvnHist(PrdctVo prdctVo)throws Exception;
	public Map getColorList()throws Exception;
	public Map getMtrlList()throws Exception;
	public Integer getPrdctId(PrdctVo prdctVo)throws Exception;
	public Map getPrdctByNFC(PrdctVo prdctVo)throws Exception;
	public String getImgPath(ShopVo shopVo)throws Exception;
	public Map getMorePrdct(ShopVo shpoVo)throws Exception;
	public PrdctVo getInvnEditForm(PrdctVo prdctVo)throws Exception;
	public PrdctVo getLensInvnEditForm(PrdctVo prdctVo)throws Exception;
	public PrdctVo getClensInvnEditForm(PrdctVo prdctVo)throws Exception;
	public PrdctVo getClensAccInvnEditForm(PrdctVo prdctVo)throws Exception;
	public String modifyInvnPrdct(PrdctVo prdctVo)throws Exception;
	public String modifyLensInvnPrdct(PrdctVo prdctVo)throws Exception;
	public String modifyClensInvnPrdct(PrdctVo prdctVo)throws Exception;
	public String modifyClensAccInvnPrdct(PrdctVo prdctVo)throws Exception;
	public void delHistData(PrdctVo prdctVo)throws Exception;
	public void delLensHistData(PrdctVo prdctVo)throws Exception;
	public void delClensHistData(PrdctVo prdctVo)throws Exception;
	public void delClensAccHistData(PrdctVo prdctVo)throws Exception;
	public Integer insertDiffClr(PrdctVo prdctVo)throws Exception;
	public Integer insertDiffLens(PrdctVo prdctVo)throws Exception;
	public Integer insertDiffClens(PrdctVo prdctVo)throws Exception;
	
	public Integer insertDiffAcc(PrdctVo prdctVo)throws Exception;
	public Map getMtrl(PrdctVo prdctVo)throws Exception;
	public Map getFunction(PrdctVo prdctVo)throws Exception;
	public Map getPrdctListLens(PrdctVo prdctVo)throws Exception;
	public Map getPrdctListClens(PrdctVo prdctVo)throws Exception;
	public Map getLensData(PrdctVo prdctVo)throws Exception;
	public PrdctVo getPrdctPrc(PrdctVo prdctVo)throws Exception;
	public PrdctVo getClensPrc(PrdctVo prdctVo)throws Exception;
	public PrdctVo getClensAccPrc(PrdctVo prdctVo)throws Exception;
	public String addInvnLensData(PrdctVo prdctVo)throws Exception;
	public String addInvnClensData(PrdctVo prdctVo)throws Exception;
	public String addInvnClensAccData(PrdctVo prdctVo)throws Exception;
	public Map getInvnLensList(PrdctVo prdctVo)throws Exception;
	public Map getInvnClensList(PrdctVo prdctVo)throws Exception;
	public Map getInvnClensAccList(PrdctVo prdctVo)throws Exception;
	public String addLens(PrdctVo prdctVo)throws Exception;
	public String addClens(PrdctVo prdctVo)throws Exception;
	public String addClensAcc(PrdctVo prdctVo)throws Exception;
	public String addEtc(PrdctVo prdctVo)throws Exception;
	public Map getClensTyList(PrdctVo prdctVo)throws Exception;
	public Map getClensTyList2(PrdctVo prdctVo)throws Exception;
	public Map getClensList(PrdctVo prdctVo)throws Exception;
	public Map getEtcList(PrdctVo prdctVo)throws Exception;
	public Map getPrdctUnit(PrdctVo prdctVo)throws Exception;
	public String getAccId(PrdctVo prdctVo)throws Exception;
	public String addReqeustFrame(PrdctVo prdctVo)throws Exception;
	public String addReqeustlens(PrdctVo prdctVo)throws Exception;
	public String addReqeustClens(PrdctVo prdctVo)throws Exception;
	public String addReqeustAcc(PrdctVo prdctVo)throws Exception;
	public String addReqeustEtc(PrdctVo prdctVo)throws Exception;
	public Map getFrame(PrdctVo prdctVo)throws Exception;
	public PrdctVo getComPrdctEditForm(PrdctVo prdctVo)throws Exception;
	public String modifyComPrdct(PrdctVo prdctVo)throws Exception;
	public Map getComPrdct(PrdctVo prdctVo)throws Exception;
	public String addNewComPrdct(PrdctVo prdctVo)throws Exception;
	public String allowPrdct(PrdctVo prdctVo)throws Exception;
	public String rejectPrdct(PrdctVo prdctVo)throws Exception;
	public String changeComPrdctColor(PrdctVo prdctVo)throws Exception;
	public String changeBrandName(BrandVo brandVo)throws Exception;
	public String changePrdctName(PrdctVo prdctVo)throws Exception;
	public String delRequestPrdct(PrdctVo prdctVo)throws Exception;
	public Map getOrderList(PrdctVo prdctVo)throws Exception;
	public Map getDeliverList(PrdctVo prdctVo)throws Exception;
	public String deliverPrdct(PrdctVo prdctVo)throws Exception; 
	public String getPrdctCnt(PrdctVo prdctVo)throws Exception;
	public String addNewClensTy1(PrdctVo prdctVo)throws Exception;
	public String addNewClensTy2(PrdctVo prdctVo)throws Exception;
	public Map getNewTyList(PrdctVo prdctVo)throws Exception;
	public Map getNewClensTyList2(PrdctVo prdctVo)throws Exception;
	public String deleteDeliverData(PrdctVo prdctVo)throws Exception;
	public String modifyLensRate(PrdctVo prdctVo)throws Exception;
	public String modifyClensData(PrdctVo prdctVo)throws Exception;
	public String chagneAccUnit(PrdctVo prdctVo)throws Exception;
	public Map srchPrdct(PrdctVo prdctVo)throws Exception;
	public String addShopLens(PrdctVo prdctVo)throws Exception;
	public String addShopClens(PrdctVo prdctVo)throws Exception;
	public String addShopClensAcc(PrdctVo prdctVo)throws Exception;
	public Map getReceiptHeader(PrdctVo prdctVo)throws Exception;
	public Map getReceipt(PrdctVo prdctVo)throws Exception;
	public Map getReceiptLens(PrdctVo prdctVo)throws Exception;
	public Map getReceiptClens(PrdctVo prdctVo)throws Exception;
	public Map getReceiptAcc(PrdctVo prdctVo)throws Exception;
	public Map getReceiptEtc(PrdctVo prdctVo)throws Exception;
	public Map getRtnFrame(PrdctVo prdctVo)throws Exception;
	public Map getRtnLens(PrdctVo prdctVo)throws Exception;
	public Map getRtnClens(PrdctVo prdctVo)throws Exception;
	public Map getRtnAcc(PrdctVo prdctVo)throws Exception;
	public Map getRtnEtc(PrdctVo prdctVo)throws Exception;
	public String addNewLensTy(PrdctVo prdctVo)throws Exception;
	public Map showAllLensType(PrdctVo prdctVo)throws Exception;
	public String modifyPrdctCnt(PrdctVo prdctVo)throws Exception;
	public PrdctVo getRtnMsg(PrdctVo prdctVo)throws Exception;
	public String allowRtn(PrdctVo prdctVo)throws Exception;
	public String modifyShopInvn(PrdctVo prdctVo)throws Exception;
	public Map selectCom(PrdctVo prdctVo)throws Exception;
	public Map getTradeData(PrdctVo prdctVo)throws Exception;
	public Map getTradeGroupData(PrdctVo prdctVo)throws Exception;
	public Map getTradeListAll(PrdctVo prdctVo)throws Exception;
	public Map getTradeListAllC(PrdctVo prdctVo)throws Exception;
	public Map getTradeDataCsv(PrdctVo prdctVo)throws Exception;
	public Map getTradeDataCsvS(PrdctVo prdctVo)throws Exception;
}
