package com.gallery.sale;

import com.gallery.payment.PaymentVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SaleMapper {
    void addSale(SaleVo value);
    void modifyHistId(SaleVo value);
    void modifyResult(SaleVo value);
    void mlistSale(SaleVo value);
    void renewalTaxBigo(SaleVo value);
    void modifyResultOgnPrice(SaleVo value);
    void modifyResultPayment(SaleVo value);
    void modifySale(SaleVo value);
    void addCstmrHst(SaleVo value);
    void removeSalePrdct(SalePrdctVo value);
    void removeNewSalePrdct(SalePrdctVo value);
    void removeSale(SaleVo value);
    void modifyCardPayDate(SaleVo value);
    void modifySaleDate(SaleVo value);
    void saleMemoUpdate(SaleVo value);
    void modifyCstmrHst(SaleVo value);
    void delSaleId(SaleVo value);
    void salejobpaymentUpdate(SaleVo value);
    void salepaymentUpdate(SaleVo value);
    void addSalePrdct(SalePrdctVo value);
    void updateAsmblySalePrdctOff(SalePrdctVo value);
    void updateInformSalePrdctOff(SalePrdctVo value);
    void updateInformSalePrdctOffNew(SalePrdctVo value);
    void updateAsmblyNewSalePrdctOff(SalePrdctVo value);
    void updateDlvrySalePrdctOff(SalePrdctVo value);
    void updateDlvryNewSalePrdctOff(SalePrdctVo value);
    void incCntSalePrdctOff(SalePrdctVo value);
    void decCntSalePrdctOff(SalePrdctVo value);
    void incCntSalePrdctOffNew(SalePrdctVo value);
    void decCntSalePrdctOffNew(SalePrdctVo value);
    void decCntFrameInvn(SalePrdctVo value);
    void decCntLensInvn(SalePrdctVo value);
    void decCntCLensInvn(SalePrdctVo value);
    void decCntAccInvn(SalePrdctVo value);
    void decCntInvn(SalePrdctVo value);
    void incCntAccInvn(SalePrdctVo value);
    void incCntFrameInvn(SalePrdctVo value);
    void incCntCLensInvn(SalePrdctVo value);
    void incCntInvn(SalePrdctVo value);
    void addFrameInvnHist(SalePrdctVo value);
    void addCLensInvnHist(SalePrdctVo value);
    void addLensInvnHist(SalePrdctVo value);
    void addInvnHist(SalePrdctVo value);
    void addAccInvnHist(SalePrdctVo value);
    void removeInvnHist(SalePrdctVo value);
    void incCntLensInvn(SalePrdctVo value);
    void modifySaleCancel(PaymentVo value);
    String getSaleMemo(SaleVo value);
    Integer countSale(SaleVo value);
    Integer countSaleCstmr(SaleVo value);
    Integer countSalePrdct(SalePrdctVo value);
    Integer countSalePrdctNew(SalePrdctVo value);
    Integer checkInvnHist(SalePrdctVo value);
    Integer checkFrameInvnHist(SalePrdctVo value);
    Integer checkLensInvnHist(SalePrdctVo value);
    Integer checkClensInvnHist(SalePrdctVo value);
    Integer checkAccInvnHist(SalePrdctVo value);
    Integer getSalePrdct(SalePrdctVo value);
    Integer countSalePrdctSaleId(SalePrdctVo value);
    Integer countNewSalePrdctSaleId(SalePrdctVo value);
    Integer countAsmbly(SalePrdctVo value);
    Integer newcountAsmbly(SalePrdctVo value);
    Integer countDlvry(SalePrdctVo value);
    Integer newcountDlvry(SalePrdctVo value);
    SalePrdctVo listSalePrdct(SaleVo value);
    SalePrdctVo listPastPurchasedFrame(SaleVo value);
    SalePrdctVo listPastPurchasedLens(SaleVo value);
    SalePrdctVo listPastPurchasedClens(SaleVo value);
    SalePrdctVo listPastPurchasedOld(SaleVo value);
    SalePrdctVo listPastPurchasedNewPrdct(SaleVo value);
    SalePrdctVo getSalePrdctOff(SalePrdctVo value);
    SalePrdctVo getNewSalePrdctOff(SalePrdctVo value);
    SaleVo listSale(SaleVo value);
    SaleVo getBillInfo(SaleVo value);
    List<SaleVo> getPayCardInfo(SaleVo value);
    List<SaleVo> getPaymentList(SaleVo value);
    SaleVo getSale(SaleVo value);
    SaleVo getSaleForResult(SaleVo value);
    List<SaleVo> listSaleOffHist(SaleVo value);
    List<SaleVo> listSaleOffHistOld(SaleVo value);
    SaleVo getSaleForCstmrAndResult(SaleVo value);

    Integer getDlvryCheck(SalePrdctVo value);
}
